#!/usr/bin/python

from termcolor import colored
from opencc import OpenCC
from sys import argv, exit
import webbrowser

if len(argv) != 2:
    print("Usage: cnforvo word")
    print("    word should be in zh_TW (traditional Chinese)")
    exit(1)

trad = argv[1]
conv = OpenCC('s2tw').convert(trad)
simp = OpenCC('tw2s').convert(trad)

if conv != trad:
    warn = colored('WARNING', 'yellow')
    text = f"{warn}: Input probably in Simplified Chinese, trying automatic conversion"
    print(text)

    trad = conv

words = set([trad, simp])
for w in words:
    webbrowser.open(f"https://forvo.com/word/{w}/#zh")
